/ Strategic Objectives Status
...paste so_status_widget.js content...

// Strategic Objectives Summary
...paste so_status_summary_widget.js content...

// Strategic OKR Summary
...paste so_status_summary_kr_widget.js content...
